### PR TITLE
Import fixes

### PR DESCRIPTION
**Pull request by rotimi-best**
This runs well for me

### CODE REVIEW

**Comment by Cobwebster** [comment]
So i'm kinda confused about the changes, what actually did you change? because I thought i already did

import Col from "react-bootstrap/Col";

**Comment by rotimi-best** [comment]
I basically just changed typos and that was all. Look at my commit https://github.com/Cobwebster/SuffolkDaily/pull/1/commits/92c18bb1b75d4c761801aba5ae7b98873aa4bc7a

**Comment by rotimi-best** [comment]
Nothing special btw. You just had some namings wrong and I saw it in my console

**Comment by rotimi-best** [comment]
in summary the styles worked when I ran build. If you watched the [video](https://youtu.be/_HwgoXMxQXY)

**Comment by Cobwebster** [comment]
When I run build, do I grab the file thats made in

\suffolkdaily\.next\server\static?

because I changed the import on index and it still seems to be styleless when I use those files.

**Comment by Cobwebster** [comment]
I should also clarify that I get the styling on npm start also, but when I double click the .html file or upload to my server, no styles.

**Comment by rotimi-best** [comment]
> When I run build, do I grab the file thats made in
> 
> \suffolkdaily.next\server\static?
> 
> because I changed the import on index and it still seems to be styleless when I use those files.

Just run the following command: `npm run build` && `npm start` then go to localhost:3000. Like [here](https://nextjs.org/docs/deployment#self-hosting)





> I should also clarify that I get the styling on npm start also, but when I double click the .html file or upload to my server, no styles.

You don't need to upload anything to any server, just use zeit to deploy by following these [instructions](https://nextjs.org/learn/basics/deploying-a-nextjs-app) very simple

**Comment by Cobwebster** [comment]
Is there not just a simple way to generate a static site on my environment on my pc? I kinda just wanna fix the isssue with imports not working on the static one via build

I have to setup some kind of nodejs zeit setup to deploy? 

That being said I am now watching this,
https://www.youtube.com/watch?v=1Bfb8pSvoQo

but again i'd rather just fix it for static

**Comment by rotimi-best** [comment]
> Is there not just a simple way to generate a static site on my environment on my pc?

Did you run the commands I asked you to (`npm run build && npm start` then go to localhost:3000)?

I see the problem, you don't understand the purpose of Next.js. Next.js is server side rendered so running it on a port is REQUIRED. 

> Is there not just a simple way to generate a static site on my environment on my pc?

For static sites go use create-react-app cause this is a single page application(SPA) however for Next.js it isn't a SPA it is a Server Side Rendered App that is why you need to run it on a server.

Read the difference between the both of them.

**Comment by rotimi-best** [comment]
To run locally follow the commands I wrote earlier.

**Comment by Cobwebster** [comment]
Server side rendering is why I picked NextJS, I need to host it on my apache2 server though so I can point a domain to it.

npm run build && npm start - just makes it run on my local host which is useless to me :/

I'm just struggling to understand how I would get it off my PC and onto my server. Do I just upload the whole project to my server and then use those commands? 

Example - this is the server, http://64.225.35.199/

**Comment by Cobwebster** [comment]
Thanks for the support, really appreciate it. Its a weird concept to me having my whole project on the server and running the build/start commands there as appose to just drag and drop. 

Thanks again.

**Pull request merged**
